version: '3'
services:
  storage:
    container_name: summit-group
    build:
      context: ../
      dockerfile: ./Gts.SummitGroup.Geodata.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "410:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock